### ISSUE TITLE
Java port

### ISSUE THREAD

**Issue by Osiris-Team** [pidgy/obs#1]
Hey @pidgy

would you be interested in porting this to Java? I would need it in one of my projects, more specifically my Remote-Desktop project, to provide more efficient screen sharing.

**Comment by pidgy** [comment]
> Hey @pidgy
> 
> would you be interested in porting this to Java? I would need it in one of my projects, more specifically my Remote-Desktop project, to provide more efficient screen sharing.

No thanks!
